{% set name = "seastats" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seastats-{{ version }}.tar.gz
  sha256: 08c7163d76a67663e80be930671df286f4ad20ca74a6a48067a623b3c43a5024

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pyextremes

test:
  imports:
    - seastats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oceanmodeling/seastats
  summary: package for metocean statistics
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brey
    - pmav99
    - tomsail
