{% set name = "seastats" %}
{% set version = "0.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seastats-{{ version }}.tar.gz
  sha256: ca244cb8e014e31082bdfd7d424a09af1bf118225927686f4b7ac1f198ab103a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pyextremes

test:
  imports:
    - seastats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oceanmodeling/seastats
  summary: package for metocean statistics
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brey
    - pmav99
    - tomsail
